### ISSUE TITLE
ディレクトリを移動すると実行ファイルとして存在するコマンドが実行できなくなる

### ISSUE THREAD

**Issue by kaonasi-biwa** [kotonone/kotonemu#5]
### Summary
`/bin/`に実行ファイルとして存在するコマンドが、`/dev/`や`/root/`に移動したときに実行できなくなっています。
### Expected Behavior
`/root/`などに移動したときにもコマンドが実行できてほしい。
### Actual Behavior
カーネルパニックを起こしてしまう。
![image](https://github.com/kotonone/kotonemu/assets/85387717/ce64a991-8729-49c1-a2d1-95dd0f249e0b)
### Steps to Reproduce
1. `cd /root/`を実行する
2. `fsh`など任意の実行ファイルを実行しようとする
3. カーネルパニック
### Do you want to address this bug yourself?
- [ ] Yes, I will patch the bug myself and send a pull request

**Comment by kotonefami** [comment]
#4 で修正済み

**Comment by kaonasi-biwa** [comment]
ｿｳﾅﾉ!?!?

**Comment by kotonefami** [comment]
嘘ついたごめーんｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗｗ寝ぼけてましたｗｗｗｗｗｗｗｗｗｗｗｗｗｗ

**Comment by kaonasi-biwa** [comment]
ﾊｲｯ(((

**Comment by kotonefami** [comment]
3aab125e70bda5a3c256851dfd74d147e2b0a42b で修正済み
